# Generated by Django 5.0.4 on 2024-07-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polls', '0002_auto_20240428_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetAndFinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('tele', models.CharField(max_length=15)),
                ('desc', models.CharField()),
            ],
        ),
    ]
