# Generated by Django 5.0.4 on 2024-07-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='CeoOfBac',
        ),
        migrations.RemoveField(
            model_name='about',
            name='Ceo_Name',
        ),
        migrations.RemoveField(
            model_name='about',
            name='Chair_Name',
        ),
        migrations.RemoveField(
            model_name='about',
            name='Finance_Name',
        ),
        migrations.RemoveField(
            model_name='about',
            name='ImageEdit',
        ),
        migrations.RemoveField(
            model_name='about',
            name='Mission',
        ),
        migrations.RemoveField(
            model_name='about',
            name='Planning',
        ),
        migrations.RemoveField(
            model_name='about',
            name='Planning_Name',
        ),
        migrations.RemoveField(
            model_name='about',
            name='Services',
        ),
        migrations.RemoveField(
            model_name='about',
            name='Stratigic1',
        ),
        migrations.RemoveField(
            model_name='about',
            name='Stratigic2',
        ),
        migrations.RemoveField(
            model_name='about',
            name='Stratigic3',
        ),
        migrations.RemoveField(
            model_name='about',
            name='Stratigic4',
        ),
        migrations.RemoveField(
            model_name='about',
            name='Stratigic5',
        ),
        migrations.RemoveField(
            model_name='about',
            name='Stratigicplan',
        ),
        migrations.RemoveField(
            model_name='about',
            name='ViceChairman',
        ),
        migrations.RemoveField(
            model_name='about',
            name='Vice_Chair_Name',
        ),
        migrations.RemoveField(
            model_name='about',
            name='Vission',
        ),
        migrations.RemoveField(
            model_name='about',
            name='chairman',
        ),
        migrations.RemoveField(
            model_name='about',
            name='dir_services_Name',
        ),
        migrations.RemoveField(
            model_name='about',
            name='finance',
        ),
        migrations.RemoveField(
            model_name='agriculture',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='agriculture',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='bfinance',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='bfinance',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='ceo',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='ceo',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='chairm',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='chairm',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='community',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='community',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='councilmember',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='councilmember',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='education',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='education',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='fearture',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='fearture',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='health',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='health',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='home',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='home',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='intpartner',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='intpartner',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='land',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='land',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='misandvis',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='misandvis',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='plananddev',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='plananddev',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='powandfun',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='powandfun',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='ratesandtaxe',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='ratesandtaxe',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='sanitation',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='sanitation',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='service',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='service',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='services',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='services',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='staffsofcouncil',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='staffsofcouncil',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='team',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='team',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='last_name',
        ),
        migrations.AddField(
            model_name='about',
            name='content',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='page_images/'),
        ),
        migrations.AddField(
            model_name='about',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='agriculture',
            name='content',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='agriculture',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='page_images/'),
        ),
        migrations.AddField(
            model_name='agriculture',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bfinance',
            name='content',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bfinance',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='page_images/'),
        ),
        migrations.AddField(
            model_name='bfinance',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ceo',
            name='content',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ceo',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='page_images/'),
        ),
        migrations.AddField(
            model_name='ceo',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='chairm',
            name='content',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='chairm',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='page_images/'),
        ),
        migrations.AddField(
            model_name='chairm',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='content',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='page_images/'),
        ),
        migrations.AddField(
            model_name='community',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='content',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='page_images/'),
        ),
        migrations.AddField(
            model_name='contact',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='councilmember',
            name='content',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='councilmember',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='page_images/'),
        ),
        migrations.AddField(
            model_name='councilmember',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='content',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='page_images/'),
        ),
        migrations.AddField(
            model_name='education',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fearture',
            name='content',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='fearture',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='page_images/'),
        ),
        migrations.AddField(
            model_name='fearture',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='health',
            name='content',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='health',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='page_images/'),
        ),
        migrations.AddField(
            model_name='health',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='content',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='page_images/'),
        ),
        migrations.AddField(
            model_name='home',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='intpartner',
            name='content',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='intpartner',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='page_images/'),
        ),
        migrations.AddField(
            model_name='intpartner',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='land',
            name='content',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='land',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='page_images/'),
        ),
        migrations.AddField(
            model_name='land',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='misandvis',
            name='content',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='misandvis',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='page_images/'),
        ),
        migrations.AddField(
            model_name='misandvis',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='plananddev',
            name='content',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='plananddev',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='page_images/'),
        ),
        migrations.AddField(
            model_name='plananddev',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='powandfun',
            name='content',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='powandfun',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='page_images/'),
        ),
        migrations.AddField(
            model_name='powandfun',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='content',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='page_images/'),
        ),
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='content',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='page_images/'),
        ),
        migrations.AddField(
            model_name='publication',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ratesandtaxe',
            name='content',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ratesandtaxe',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='page_images/'),
        ),
        migrations.AddField(
            model_name='ratesandtaxe',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sanitation',
            name='content',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sanitation',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='page_images/'),
        ),
        migrations.AddField(
            model_name='sanitation',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='content',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='page_images/'),
        ),
        migrations.AddField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='content',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='page_images/'),
        ),
        migrations.AddField(
            model_name='services',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='staffsofcouncil',
            name='content',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='staffsofcouncil',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='page_images/'),
        ),
        migrations.AddField(
            model_name='staffsofcouncil',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='content',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='page_images/'),
        ),
        migrations.AddField(
            model_name='team',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='content',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='page_images/'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
