# Generated by Django 5.0.4 on 2024-08-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_contactus_index_delete_contact_delete_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name', models.CharField(blank=True, max_length=200, null=True)),
                ('content_p', models.TextField(null=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='img/')),
            ],
        ),
        migrations.DeleteModel(
            name='Index',
        ),
    ]
