# Generated by Django 5.0.4 on 2024-08-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_home_delete_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='title_name',
            new_name='Descriptio_ceo',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='content_p',
            new_name='Jurisdic_of_Council',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='featured_image',
            new_name='image_about_BAC',
        ),
        migrations.AddField(
            model_name='home',
            name='Description_busim',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='Description_chairm',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='Description_headqut',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='Description_nurs',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='Description_teacher',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='Description_vice',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='Natural_Resoures',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='Pop_density',
            field=models.FloatField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='Population',
            field=models.FloatField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='Public_and_Enviro_Health',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='Road_Ntw_Infras',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='Testim_busim',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='Testim_name_teacher',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='Testim_nurs',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='Title_name_ceo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='Title_name_chairman',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='Title_name_vice',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='Yearly_Pop_shift',
            field=models.FloatField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='aerial_space',
            field=models.FloatField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='content_BAC',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='content_Local_Tailored',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='content_about_BAC',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='description_bAC',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='image_basseAC',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AddField(
            model_name='home',
            name='telephone_CallUs',
            field=models.FloatField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='telephone_reach_out',
            field=models.FloatField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='testim_image_busim',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AddField(
            model_name='home',
            name='testim_image_nurs',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AddField(
            model_name='home',
            name='testim_image_teacher',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AddField(
            model_name='home',
            name='title_image_ceo',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AddField(
            model_name='home',
            name='title_image_chairm',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AddField(
            model_name='home',
            name='title_image_vice',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AddField(
            model_name='home',
            name='words_busim',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='words_nurs',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='words_teach',
            field=models.TextField(null=True),
        ),
    ]
