# Generated by Django 5.0.4 on 2024-08-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_rename_title_name_home_descriptio_ceo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='Aerial_space',
            field=models.FloatField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='quotation_Nat_res',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='quotation_env_hlth',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='quotation_infras',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
