# Generated by Django 5.0.4 on 2024-08-06 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_home_aerial_space_home_quotation_nat_res_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='Aerial_space',
        ),
        migrations.RemoveField(
            model_name='home',
            name='quotation_Nat_res',
        ),
        migrations.RemoveField(
            model_name='home',
            name='quotation_env_hlth',
        ),
        migrations.RemoveField(
            model_name='home',
            name='quotation_infras',
        ),
    ]
