# Generated by Django 5.0.4 on 2024-08-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_rename_jurisdic_of_council_home_content_p_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='content_p',
            new_name='content_BAC',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='title_name',
            new_name='desc_BAC',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='featured_image',
            new_name='image_BAC',
        ),
        migrations.AlterField(
            model_name='about',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
