# Generated by Django 5.0.4 on 2024-08-06 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_home_aerial_space_home_quote_ntw_infras_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='quote_Nat_Resourse',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='quote_enviro_health',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
