# Generated by Django 5.0.4 on 2024-08-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_alter_home_telephone_callus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='telephone_CallUs',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='telephone_reach_out',
            field=models.CharField(blank=True, null=True),
        ),
    ]
