# Generated by Django 5.0.4 on 2024-08-07 07:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_alter_home_telephone_callus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='telephone_reach_out',
            field=models.CharField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)]),
        ),
    ]
