# Generated by Django 5.0.4 on 2024-08-07 07:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_alter_home_telephone_reach_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='telephone_CallUs',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)]),
        ),
    ]
