# Generated by Django 5.0.4 on 2024-08-07 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_rename_featured_image_about_image_about_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='Aboutus',
        ),
    ]
