# Generated by Django 5.0.4 on 2024-08-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0025_rename_about_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='Councillors',
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='constituencies',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='telephone_CallUs',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='unity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='villages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='wards',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
