# Generated by Django 5.0.4 on 2024-08-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0028_powers_and_function_delete_powandfun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powers_and_function',
            name='criti_li1',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='powers_and_function',
            name='criti_li10',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='powers_and_function',
            name='criti_li11',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='powers_and_function',
            name='criti_li115',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='powers_and_function',
            name='criti_li116',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='powers_and_function',
            name='criti_li117',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='powers_and_function',
            name='criti_li118',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='powers_and_function',
            name='criti_li12',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='powers_and_function',
            name='criti_li13',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='powers_and_function',
            name='criti_li14',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='powers_and_function',
            name='criti_li19',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='powers_and_function',
            name='criti_li2',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='powers_and_function',
            name='criti_li20',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='powers_and_function',
            name='criti_li3',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='powers_and_function',
            name='criti_li4',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='powers_and_function',
            name='criti_li5',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='powers_and_function',
            name='criti_li6',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='powers_and_function',
            name='criti_li7',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='powers_and_function',
            name='criti_li8',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='powers_and_function',
            name='criti_li9',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
