# Generated by Django 5.0.4 on 2024-08-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0030_remove_powers_and_function_desc_cri_leg_para2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Powers_and_Functions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('powers_sct48_li1', models.CharField(blank=True, max_length=300, null=True)),
                ('powers_sct48_li2', models.CharField(blank=True, max_length=300, null=True)),
                ('powers_sct48_li3', models.CharField(blank=True, max_length=300, null=True)),
                ('powers_sct48_li4', models.CharField(blank=True, max_length=300, null=True)),
                ('powers_sct48_li5', models.CharField(blank=True, max_length=300, null=True)),
                ('powers_sct48_li6', models.CharField(blank=True, max_length=300, null=True)),
                ('powers_sct48_li7', models.CharField(blank=True, max_length=300, null=True)),
                ('legis_pow_li1', models.CharField(blank=True, max_length=300, null=True)),
                ('legis_pow_li2', models.CharField(blank=True, max_length=300, null=True)),
                ('miscel_pow_li1', models.CharField(blank=True, max_length=300, null=True)),
                ('miscel_pow_li2', models.CharField(blank=True, max_length=300, null=True)),
                ('miscel_pow_li3', models.CharField(blank=True, max_length=300, null=True)),
                ('miscel_pow_li4', models.CharField(blank=True, max_length=300, null=True)),
                ('image_functions', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('functions_of_BAC', models.TextField(blank=True, null=True)),
                ('education_li1', models.TextField(blank=True, null=True)),
                ('education_li2', models.TextField(blank=True, null=True)),
                ('education_li3', models.TextField(blank=True, null=True)),
                ('education_li4', models.TextField(blank=True, null=True)),
                ('education_li5', models.TextField(blank=True, null=True)),
                ('education_li6', models.TextField(blank=True, null=True)),
                ('education_li7', models.TextField(blank=True, null=True)),
                ('education_li8', models.TextField(blank=True, null=True)),
                ('education_li9', models.TextField(blank=True, null=True)),
                ('education_li10', models.TextField(blank=True, null=True)),
                ('education_li11', models.TextField(blank=True, null=True)),
                ('image_other_powers', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('other_powers', models.TextField(blank=True, null=True)),
                ('other_powers_li1', models.TextField(blank=True, null=True)),
                ('other_powers_li2', models.TextField(blank=True, null=True)),
                ('other_powers_li3', models.TextField(blank=True, null=True)),
                ('other_powers_li4', models.TextField(blank=True, null=True)),
                ('criti_legal_policy_para1', models.TextField(blank=True, null=True)),
                ('Desc_cri_leg_para2', models.TextField(blank=True, null=True)),
                ('criti_li1', models.CharField(blank=True, max_length=300, null=True)),
                ('criti_li2', models.CharField(blank=True, max_length=300, null=True)),
                ('criti_li3', models.CharField(blank=True, max_length=300, null=True)),
                ('criti_li4', models.CharField(blank=True, max_length=300, null=True)),
                ('criti_li5', models.CharField(blank=True, max_length=300, null=True)),
                ('criti_li6', models.CharField(blank=True, max_length=300, null=True)),
                ('criti_li7', models.CharField(blank=True, max_length=300, null=True)),
                ('criti_li8', models.CharField(blank=True, max_length=300, null=True)),
                ('criti_li9', models.CharField(blank=True, max_length=300, null=True)),
                ('criti_li10', models.CharField(blank=True, max_length=300, null=True)),
                ('criti_li11', models.CharField(blank=True, max_length=300, null=True)),
                ('criti_li12', models.CharField(blank=True, max_length=300, null=True)),
                ('criti_li13', models.CharField(blank=True, max_length=300, null=True)),
                ('criti_li14', models.CharField(blank=True, max_length=300, null=True)),
                ('criti_li115', models.CharField(blank=True, max_length=300, null=True)),
                ('criti_li116', models.CharField(blank=True, max_length=300, null=True)),
                ('criti_li117', models.CharField(blank=True, max_length=300, null=True)),
                ('criti_li118', models.CharField(blank=True, max_length=300, null=True)),
                ('criti_li19', models.CharField(blank=True, max_length=300, null=True)),
                ('criti_li20', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Powers_and_Function',
        ),
    ]
