# Generated by Django 5.0.4 on 2024-08-11 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0031_powers_and_functions_delete_powers_and_function'),
    ]

    operations = [
        migrations.RenameField(
            model_name='powers_and_functions',
            old_name='criti_li115',
            new_name='criti_li15',
        ),
        migrations.RenameField(
            model_name='powers_and_functions',
            old_name='criti_li116',
            new_name='criti_li16',
        ),
        migrations.RenameField(
            model_name='powers_and_functions',
            old_name='criti_li117',
            new_name='criti_li17',
        ),
        migrations.RenameField(
            model_name='powers_and_functions',
            old_name='criti_li118',
            new_name='criti_li18',
        ),
    ]
