# Generated by Django 5.0.4 on 2024-08-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0032_rename_criti_li115_powers_and_functions_criti_li15_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestiM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_words_pple', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('Testim_name_teacher', models.CharField(blank=True, max_length=200, null=True)),
                ('words_teach', models.TextField(blank=True, null=True)),
                ('Description_teacher', models.CharField(blank=True, max_length=200, null=True)),
                ('testim_image_teacher', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('Testim_nurs', models.CharField(blank=True, max_length=200, null=True)),
                ('words_nurs', models.TextField(blank=True, null=True)),
                ('Description_nurs', models.CharField(blank=True, max_length=200, null=True)),
                ('testim_image_nurs', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('Testim_busim', models.CharField(blank=True, max_length=200, null=True)),
                ('words_busim', models.TextField(blank=True, null=True)),
                ('Description_busim', models.CharField(blank=True, max_length=200, null=True)),
                ('testim_image_busim', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('banna_para1', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
