# Generated by Django 5.0.4 on 2024-08-14 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0033_testim_delete_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='chairman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mandate_para', models.TextField(max_length=200, null=True)),
                ('image_chaim', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('content_p1', models.TextField(blank=True, max_length=500, null=True)),
                ('content_p2', models.TextField(blank=True, max_length=500, null=True)),
                ('content_p3', models.TextField(blank=True, max_length=500, null=True)),
                ('content_p4', models.TextField(blank=True, max_length=500, null=True)),
                ('content_p5', models.TextField(blank=True, max_length=500, null=True)),
                ('content_p6', models.TextField(blank=True, max_length=500, null=True)),
                ('content_p7', models.TextField(blank=True, max_length=500, null=True)),
                ('content_p8', models.TextField(blank=True, max_length=500, null=True)),
                ('content_p9', models.TextField(blank=True, max_length=500, null=True)),
                ('content_p10', models.TextField(blank=True, max_length=500, null=True)),
                ('content_p11', models.TextField(blank=True, max_length=500, null=True)),
                ('content_p12', models.TextField(blank=True, max_length=500, null=True)),
                ('content_p13', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='councilmembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_chair', models.CharField(blank=True, max_length=200, null=True)),
                ('title_image_chair', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('Title_name_chair', models.CharField(max_length=200, null=True)),
                ('name_vchair', models.CharField(blank=True, max_length=200, null=True)),
                ('title_image_Vchair', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('Title_name_vchair', models.CharField(max_length=200, null=True)),
                ('name_commun', models.CharField(blank=True, max_length=200, null=True)),
                ('title_image_commun', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('Title_name_commun', models.CharField(max_length=200, null=True)),
                ('name_plan', models.CharField(blank=True, max_length=200, null=True)),
                ('title_image_plan', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('Title_name_plan', models.CharField(max_length=200, null=True)),
                ('name_finas', models.CharField(blank=True, max_length=200, null=True)),
                ('title_image_finas', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('Title_name_finas', models.CharField(max_length=200, null=True)),
                ('name_yp', models.CharField(blank=True, max_length=200, null=True)),
                ('title_image_yp', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('Title_name_yp', models.CharField(max_length=200, null=True)),
                ('name_bget', models.CharField(blank=True, max_length=200, null=True)),
                ('title_image_bget', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('Title_name_bget', models.CharField(max_length=200, null=True)),
                ('name_IT', models.CharField(blank=True, max_length=200, null=True)),
                ('title_image_IT', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('Title_name_IT', models.CharField(max_length=200, null=True)),
                ('name_sec', models.CharField(blank=True, max_length=200, null=True)),
                ('title_image_sec', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('Title_name_sec', models.CharField(max_length=200, null=True)),
                ('name_sen_RVC', models.CharField(blank=True, max_length=200, null=True)),
                ('title_image_RVC', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('Title_name_RVC', models.CharField(max_length=200, null=True)),
                ('name_ass_acc', models.CharField(blank=True, max_length=200, null=True)),
                ('title_image_acc', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('Title_name_acc', models.CharField(max_length=200, null=True)),
                ('name_plumb', models.CharField(blank=True, max_length=200, null=True)),
                ('title_image_plumb', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('Title_name_plumb', models.CharField(max_length=200, null=True)),
                ('name_assAcc', models.CharField(blank=True, max_length=200, null=True)),
                ('title_image_assAcc', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('Title_name_assAcc', models.CharField(max_length=200, null=True)),
                ('name_plann', models.CharField(blank=True, max_length=200, null=True)),
                ('title_image_plann', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('Title_name_plannn', models.CharField(max_length=200, null=True)),
                ('name_ratesM', models.CharField(blank=True, max_length=200, null=True)),
                ('title_image_ratesM', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('Title_name_ratesM', models.CharField(max_length=200, null=True)),
                ('name_mason', models.CharField(blank=True, max_length=200, null=True)),
                ('title_image_mason', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('Title_name_mason', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ChairM',
        ),
        migrations.DeleteModel(
            name='CouncilMember',
        ),
    ]
