# Generated by Django 5.0.4 on 2024-08-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0034_chairman_councilmembers_delete_chairm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ceo',
            name='content',
        ),
        migrations.RemoveField(
            model_name='ceo',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='ceo',
            name='title',
        ),
        migrations.AddField(
            model_name='ceo',
            name='content_p1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ceo',
            name='content_p10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ceo',
            name='content_p11',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ceo',
            name='content_p12',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ceo',
            name='content_p13',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ceo',
            name='content_p2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ceo',
            name='content_p3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ceo',
            name='content_p4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ceo',
            name='content_p5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ceo',
            name='content_p6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ceo',
            name='content_p7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ceo',
            name='content_p8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ceo',
            name='content_p9',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ceo',
            name='image_ceo',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AddField(
            model_name='ceo',
            name='mandate_para',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chairman',
            name='content_p1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chairman',
            name='content_p10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chairman',
            name='content_p11',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chairman',
            name='content_p12',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chairman',
            name='content_p13',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chairman',
            name='content_p2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chairman',
            name='content_p3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chairman',
            name='content_p4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chairman',
            name='content_p5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chairman',
            name='content_p6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chairman',
            name='content_p7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chairman',
            name='content_p8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chairman',
            name='content_p9',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chairman',
            name='mandate_para',
            field=models.TextField(blank=True, null=True),
        ),
    ]
