# Generated by Django 5.0.4 on 2024-08-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0035_remove_ceo_content_remove_ceo_featured_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staffs_of_Council',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_image', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('name_chair', models.CharField(blank=True, max_length=200, null=True)),
                ('title_image_chair', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('Title_name_chair', models.CharField(max_length=200, null=True)),
                ('name_vchair', models.CharField(blank=True, max_length=200, null=True)),
                ('title_image_Vchair', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('ward_vchair', models.CharField(max_length=200, null=True)),
                ('name3', models.CharField(blank=True, max_length=200, null=True)),
                ('image3', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('ward3', models.CharField(max_length=200, null=True)),
                ('name4', models.CharField(blank=True, max_length=200, null=True)),
                ('image4', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('ward4', models.CharField(max_length=200, null=True)),
                ('name5', models.CharField(blank=True, max_length=200, null=True)),
                ('image5', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('ward5', models.CharField(max_length=200, null=True)),
                ('name6', models.CharField(blank=True, max_length=200, null=True)),
                ('image6', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('ward6', models.CharField(max_length=200, null=True)),
                ('name7', models.CharField(blank=True, max_length=200, null=True)),
                ('image7', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('ward7', models.CharField(max_length=200, null=True)),
                ('name8', models.CharField(blank=True, max_length=200, null=True)),
                ('image8', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('ward8', models.CharField(max_length=200, null=True)),
                ('name9', models.CharField(blank=True, max_length=200, null=True)),
                ('image9', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('ward9', models.CharField(max_length=200, null=True)),
                ('name10', models.CharField(blank=True, max_length=200, null=True)),
                ('image10', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('ward10', models.CharField(max_length=200, null=True)),
                ('name11', models.CharField(blank=True, max_length=200, null=True)),
                ('image11', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('ward11', models.CharField(max_length=200, null=True)),
                ('name12', models.CharField(blank=True, max_length=200, null=True)),
                ('image12', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('ward12', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='StaffsofCouncil',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AddField(
            model_name='ceo',
            name='bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AddField(
            model_name='chairman',
            name='bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AddField(
            model_name='councilmembers',
            name='bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AddField(
            model_name='home',
            name='bg_image_sli1',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AddField(
            model_name='home',
            name='bg_image_sli2',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AddField(
            model_name='home',
            name='bg_image_sli3',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AddField(
            model_name='mission_and_vission',
            name='bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AddField(
            model_name='powers_and_functions',
            name='bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
