# Generated by Django 5.0.4 on 2024-08-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0036_staffs_of_council_delete_staffsofcouncil_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planing_and_Dev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_image', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('mandate_para', models.TextField(blank=True, null=True)),
                ('image_chaim', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('content_p1', models.TextField(blank=True, null=True)),
                ('content_p2', models.TextField(blank=True, null=True)),
                ('content_p3', models.TextField(blank=True, null=True)),
                ('content_p4', models.TextField(blank=True, null=True)),
                ('content_p5', models.TextField(blank=True, null=True)),
                ('content_p6', models.TextField(blank=True, null=True)),
                ('content_p7', models.TextField(blank=True, null=True)),
                ('content_p8', models.TextField(blank=True, null=True)),
                ('content_p9', models.TextField(blank=True, null=True)),
                ('content_p10', models.TextField(blank=True, null=True)),
                ('content_p11', models.TextField(blank=True, null=True)),
                ('content_p12', models.TextField(blank=True, null=True)),
                ('content_p13', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PlanandDev',
        ),
    ]
