# Generated by Django 5.0.4 on 2024-08-17 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0038_budget_finance_delete_bfinance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget_finance',
            name='content_p13',
        ),
    ]
