# Generated by Django 5.0.4 on 2024-08-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0039_remove_budget_finance_content_p13'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rates_and_Taxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pRates', models.TextField(blank=True, max_length=500, null=True)),
                ('bRates', models.TextField(blank=True, max_length=500, null=True)),
                ('sRates', models.TextField(blank=True, max_length=500, null=True)),
                ('R_image', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('blicense', models.TextField(blank=True, max_length=500, null=True)),
                ('permit', models.TextField(blank=True, max_length=500, null=True)),
                ('license_image', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('OperatMarkets', models.TextField(blank=True, max_length=500, null=True)),
                ('RegulatMarkets', models.TextField(blank=True, max_length=500, null=True)),
                ('markets_image', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('RegulatFines', models.TextField(blank=True, max_length=500, null=True)),
                ('traffic_fines', models.TextField(blank=True, max_length=500, null=True)),
                ('fines_image', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('Debts_managem', models.TextField(blank=True, max_length=500, null=True)),
                ('F_planin', models.TextField(blank=True, max_length=500, null=True)),
                ('Land_Use', models.TextField(blank=True, max_length=500, null=True)),
                ('Land_Regulations', models.TextField(blank=True, max_length=500, null=True)),
                ('Land_Management', models.TextField(blank=True, max_length=500, null=True)),
                ('Land_Transfer', models.TextField(blank=True, max_length=500, null=True)),
                ('conflick_Resolution', models.TextField(blank=True, max_length=500, null=True)),
                ('debts_image', models.ImageField(blank=True, null=True, upload_to='img/')),
            ],
        ),
        migrations.DeleteModel(
            name='RatesandTaxe',
        ),
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
