# Generated by Django 5.0.4 on 2024-08-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0040_rates_and_taxes_delete_ratesandtaxe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rates_and_taxes',
            name='Land_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='rates_and_taxes',
            name='Debts_managem',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rates_and_taxes',
            name='F_planin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rates_and_taxes',
            name='Land_Management',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rates_and_taxes',
            name='Land_Regulations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rates_and_taxes',
            name='Land_Transfer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rates_and_taxes',
            name='Land_Use',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rates_and_taxes',
            name='OperatMarkets',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rates_and_taxes',
            name='RegulatFines',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rates_and_taxes',
            name='RegulatMarkets',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rates_and_taxes',
            name='bRates',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rates_and_taxes',
            name='blicense',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rates_and_taxes',
            name='conflick_Resolution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rates_and_taxes',
            name='pRates',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rates_and_taxes',
            name='permit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rates_and_taxes',
            name='sRates',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rates_and_taxes',
            name='traffic_fines',
            field=models.TextField(blank=True, null=True),
        ),
    ]
