# Generated by Django 5.0.4 on 2024-08-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0041_rates_and_taxes_land_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='image_about',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='image_stragi',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title_image_ceo',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title_image_chairm',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title_image_finace',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title_image_planning',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title_image_service',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title_image_vice',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='agriculture',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='budget_finance',
            name='bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='budget_finance',
            name='image_finas',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='ceo',
            name='bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='ceo',
            name='image_ceo',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='chairman',
            name='bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='chairman',
            name='image_chaim',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='community',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='councilmembers',
            name='bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='councilmembers',
            name='title_image_IT',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='councilmembers',
            name='title_image_RVC',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='councilmembers',
            name='title_image_Vchair',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='councilmembers',
            name='title_image_acc',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='councilmembers',
            name='title_image_assAcc',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='councilmembers',
            name='title_image_bget',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='councilmembers',
            name='title_image_chair',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='councilmembers',
            name='title_image_commun',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='councilmembers',
            name='title_image_finas',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='councilmembers',
            name='title_image_mason',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='councilmembers',
            name='title_image_plan',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='councilmembers',
            name='title_image_plann',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='councilmembers',
            name='title_image_plumb',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='councilmembers',
            name='title_image_ratesM',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='councilmembers',
            name='title_image_sec',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='councilmembers',
            name='title_image_yp',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='education',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='home',
            name='bg_image_sli1',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='home',
            name='bg_image_sli2',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='home',
            name='bg_image_sli3',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='home',
            name='image_BAC',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='home',
            name='image_about_BAC',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='home',
            name='testim_image_busim',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='home',
            name='testim_image_nurs',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='home',
            name='testim_image_teacher',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='home',
            name='title_image_ceo',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='home',
            name='title_image_chairm',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='home',
            name='title_image_vice',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='mission_and_vission',
            name='bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='mission_and_vission',
            name='image_mis_vis',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='planing_and_dev',
            name='bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='planing_and_dev',
            name='image_plan',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='powers_and_functions',
            name='bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='powers_and_functions',
            name='image_functions',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='powers_and_functions',
            name='image_other_powers',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='rates_and_taxes',
            name='Land_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='rates_and_taxes',
            name='R_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='rates_and_taxes',
            name='debts_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='rates_and_taxes',
            name='fines_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='rates_and_taxes',
            name='license_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='rates_and_taxes',
            name='markets_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='staffs_of_council',
            name='bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='staffs_of_council',
            name='image10',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='staffs_of_council',
            name='image11',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='staffs_of_council',
            name='image12',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='staffs_of_council',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='staffs_of_council',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='staffs_of_council',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='staffs_of_council',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='staffs_of_council',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='staffs_of_council',
            name='image8',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='staffs_of_council',
            name='image9',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='staffs_of_council',
            name='title_image_Vchair',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='staffs_of_council',
            name='title_image_chair',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='testim',
            name='image_words_pple',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='testim',
            name='testim_image_busim',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='testim',
            name='testim_image_nurs',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='testim',
            name='testim_image_teacher',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
    ]
