# Generated by Django 5.0.4 on 2024-08-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0042_alter_aboutus_bg_image_alter_aboutus_image_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fearture',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='health',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='intpartner',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='land',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='sanitation',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='services',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
    ]
