# Generated by Django 5.0.4 on 2024-08-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0043_alter_fearture_featured_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_and_year1', models.CharField(blank=True, max_length=200, null=True)),
                ('Desc1', models.CharField(blank=True, max_length=500, null=True)),
                ('Sub_desc1', models.CharField(blank=True, max_length=500, null=True)),
                ('content1', models.TextField(blank=True, max_length=500, null=True)),
                ('Date_and_year2', models.CharField(blank=True, max_length=200, null=True)),
                ('Desc2', models.CharField(blank=True, max_length=500, null=True)),
                ('Sub_desc2', models.CharField(blank=True, max_length=500, null=True)),
                ('content2', models.TextField(blank=True, max_length=500, null=True)),
                ('Date_and_year3', models.CharField(blank=True, max_length=200, null=True)),
                ('Desc3', models.CharField(blank=True, max_length=500, null=True)),
                ('Sub_desc3', models.CharField(blank=True, max_length=500, null=True)),
                ('content3', models.TextField(blank=True, max_length=500, null=True)),
                ('Date_and_year4', models.CharField(blank=True, max_length=200, null=True)),
                ('Desc4', models.CharField(blank=True, max_length=500, null=True)),
                ('Sub_desc4', models.CharField(blank=True, max_length=500, null=True)),
                ('content4', models.TextField(blank=True, max_length=500, null=True)),
                ('Date_and_year5', models.CharField(blank=True, max_length=200, null=True)),
                ('Desc5', models.CharField(blank=True, max_length=500, null=True)),
                ('Sub_desc5', models.CharField(blank=True, max_length=500, null=True)),
                ('content5', models.TextField(blank=True, max_length=500, null=True)),
                ('Date_and_year6', models.CharField(blank=True, max_length=200, null=True)),
                ('Desc6', models.CharField(blank=True, max_length=500, null=True)),
                ('Sub_desc6', models.CharField(blank=True, max_length=500, null=True)),
                ('content6', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
