# Generated by Django 5.0.4 on 2024-08-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0044_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='bag_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='projects',
            name='content_price',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='Date_and_year1',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='Date_and_year5',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='Desc1',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='Desc2',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='Desc3',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='Desc4',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='Desc5',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='Desc6',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='Sub_desc1',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='Sub_desc2',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='Sub_desc3',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='Sub_desc4',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='Sub_desc5',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='Sub_desc6',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='content1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='content2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='content3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='content4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='content5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='content6',
            field=models.TextField(blank=True, null=True),
        ),
    ]
