# Generated by Django 5.0.4 on 2024-08-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0045_projects_bag_image_projects_content_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='partnerUS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('organization', models.CharField(blank=True, max_length=100, null=True)),
                ('select', models.SlugField(blank=True, null=True)),
                ('message', models.TextField()),
            ],
        ),
    ]
