# Generated by Django 5.0.4 on 2024-08-31 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0047_intpartnerus'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='bg_image_sli4',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
    ]
