# Generated by Django 5.0.4 on 2024-09-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0048_home_bg_image_sli4'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.RenameField(
            model_name='agriculture',
            old_name='featured_image',
            new_name='bg_image_agric',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='featured_image',
            new_name='bg_image_educat',
        ),
        migrations.RenameField(
            model_name='health',
            old_name='featured_image',
            new_name='bg_image_hlth',
        ),
        migrations.RenameField(
            model_name='sanitation',
            old_name='featured_image',
            new_name='bg_image_sani',
        ),
        migrations.RemoveField(
            model_name='agriculture',
            name='content',
        ),
        migrations.RemoveField(
            model_name='agriculture',
            name='title',
        ),
        migrations.RemoveField(
            model_name='education',
            name='content',
        ),
        migrations.RemoveField(
            model_name='education',
            name='title',
        ),
        migrations.RemoveField(
            model_name='health',
            name='content',
        ),
        migrations.RemoveField(
            model_name='health',
            name='title',
        ),
        migrations.RemoveField(
            model_name='sanitation',
            name='content',
        ),
        migrations.RemoveField(
            model_name='sanitation',
            name='title',
        ),
        migrations.AddField(
            model_name='agriculture',
            name='Desc_tips',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agriculture',
            name='Sub_Desc_tips',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agriculture',
            name='Tips1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agriculture',
            name='Tips2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agriculture',
            name='Tips3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agriculture',
            name='agric_para',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='Desc_tips',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='Sub_Desc_tips',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='Tips1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='Tips2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='Tips3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='educat_para',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='health',
            name='Desc_tips',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='health',
            name='Sub_Desc_tips',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='health',
            name='Tips1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='health',
            name='Tips2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='health',
            name='Tips3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='health',
            name='hlth_para',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sanitation',
            name='Desc_tips',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sanitation',
            name='Sub_Desc_tips',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sanitation',
            name='Tips1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sanitation',
            name='Tips2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sanitation',
            name='Tips3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sanitation',
            name='sani_para',
            field=models.TextField(blank=True, null=True),
        ),
    ]
