# Generated by Django 5.0.4 on 2024-09-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0049_delete_project_delete_service_delete_services_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestiM',
            new_name='Testimonial',
        ),
        migrations.RenameField(
            model_name='community',
            old_name='featured_image',
            new_name='bg_image_comu',
        ),
        migrations.RemoveField(
            model_name='community',
            name='content',
        ),
        migrations.RemoveField(
            model_name='community',
            name='title',
        ),
        migrations.AddField(
            model_name='community',
            name='Desc_tips',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='Sub_Desc_tips',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='Tips1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='Tips2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='Tips3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='comu_para',
            field=models.TextField(blank=True, null=True),
        ),
    ]
