# Generated by Django 5.0.4 on 2024-09-08 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0050_rename_testim_testimonial_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='Desc_tips',
            new_name='Desc_tips_ag',
        ),
        migrations.RenameField(
            model_name='community',
            old_name='Sub_Desc_tips',
            new_name='Sub_Desc_ag',
        ),
        migrations.RenameField(
            model_name='community',
            old_name='Tips1',
            new_name='Tips1_ag',
        ),
        migrations.RenameField(
            model_name='community',
            old_name='Tips2',
            new_name='Tips2_ag',
        ),
        migrations.RenameField(
            model_name='community',
            old_name='Tips3',
            new_name='Tips3_ag',
        ),
    ]
