# Generated by Django 5.0.4 on 2024-09-08 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0051_rename_desc_tips_community_desc_tips_ag_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='Desc_tips_ag',
            new_name='Desc_tips',
        ),
        migrations.RenameField(
            model_name='community',
            old_name='Sub_Desc_ag',
            new_name='Sub_Desc_tips',
        ),
        migrations.RenameField(
            model_name='community',
            old_name='Tips1_ag',
            new_name='Tips1',
        ),
        migrations.RenameField(
            model_name='community',
            old_name='Tips2_ag',
            new_name='Tips2',
        ),
        migrations.RenameField(
            model_name='community',
            old_name='Tips3_ag',
            new_name='Tips3',
        ),
    ]
