# Generated by Django 5.0.4 on 2024-09-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0052_rename_desc_tips_ag_community_desc_tips_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fearture',
        ),
        migrations.RenameField(
            model_name='land',
            old_name='featured_image',
            new_name='bg_image_comu',
        ),
        migrations.RemoveField(
            model_name='land',
            name='content',
        ),
        migrations.RemoveField(
            model_name='land',
            name='title',
        ),
        migrations.AddField(
            model_name='land',
            name='Desc_tips',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='land',
            name='Sub_Desc_tips',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='land',
            name='Tips1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='land',
            name='Tips2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='land',
            name='Tips3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='land',
            name='comu_para',
            field=models.TextField(blank=True, null=True),
        ),
    ]
