# Generated by Django 5.0.4 on 2024-09-15 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0053_delete_fearture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='land',
            old_name='bg_image_comu',
            new_name='bg_image',
        ),
        migrations.RenameField(
            model_name='land',
            old_name='comu_para',
            new_name='land_para',
        ),
    ]
