# Generated by Django 5.0.4 on 2024-09-16 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0054_rename_bg_image_comu_land_bg_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='title_image_ceo',
            new_name='image_ceo',
        ),
        migrations.RenameField(
            model_name='aboutus',
            old_name='title_image_chairm',
            new_name='image_chairm',
        ),
        migrations.RenameField(
            model_name='aboutus',
            old_name='title_image_finace',
            new_name='image_finace',
        ),
        migrations.RenameField(
            model_name='aboutus',
            old_name='title_image_planning',
            new_name='image_planning',
        ),
        migrations.RenameField(
            model_name='aboutus',
            old_name='title_image_service',
            new_name='image_service',
        ),
        migrations.RenameField(
            model_name='aboutus',
            old_name='title_image_vice',
            new_name='image_vice',
        ),
    ]
